#!/usr/bin/python3

import os, sys;
import subprocess;

if len(sys.argv) == 1 :
    cmd = "realpath $PWD";
    p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE );
    out, err = p.communicate();
    path = out.decode('ascii').strip();
    os.system("echo -n " + path + " | xclip");
elif len(sys.argv) == 2 :
    cmd = "realpath " + sys.argv[1];
    p = subprocess.Popen(cmd, shell=True, stdout=subprocess.PIPE, stderr=subprocess.PIPE );
    out, err = p.communicate();
    path = out.decode('ascii').strip();
    os.system("echo -n " + path + " | xclip");


